# site configuration
title: "Kelly J Andrews"
baseurl: ""
url: "http://www.kellyjandrews.com"
repo: "https://github.com/kellyjandrews/kellyjandrews.github.io/"
branch: "tree/gh-pages/"
quiet:    true

github: "https://github.com/kellyjandrews"
twitter: "https://twitter.com/kellyjandrews"
linkedin: "https://www.linkedin.com/in/kjandrews/en"
stackexchange: "https://stackexchange.com/users/2222625/kelly-j-andrews"
gems:
  - jekyll-sitemap

# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
posts:       ./_posts
pages:       ./_pages
drafts:      ./drafts
layouts_dir: ./_layouts
data_dir:    ./_data
collections: null

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"

# Handling Reading
exclude: ["less","gulp","node_modules","Gulpfile.js","package.json","scripts"]
include: ["_pages","_posts"]
encoding: "utf-8"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
